FROM centos:centos7
LABEL maintainer="NOT Sonatype <cloud-ops@sonatype.com>"

RUN yum install -y \
  curl tar zip unzip\
  && yum clean all

ARG NEXUS_VERSION=3.37.0-01

# configure java runtime
ENV JAVA_HOME=/opt/java \
  JAVA_VERSION_MAJOR=8 \
  JAVA_VERSION_MINOR=251 \
  JAVA_VERSION_BUILD=08 

# configure nexus runtime
ENV NEXUS_VERSION=$NEXUS_VERSION \
  NEXUS_HOME=/opt/sonatype/nexus \
  NEXUS_DATA=/data/nexus-data \
  NEXUS_CONTEXT=''

# install Oracle JRE
COPY "libs/jre-${JAVA_VERSION_MAJOR}u${JAVA_VERSION_MINOR}-linux-x64.rpm" "jre-${JAVA_VERSION_MAJOR}u${JAVA_VERSION_MINOR}-linux-x64.rpm"
RUN  yum install -y "jre-${JAVA_VERSION_MAJOR}u${JAVA_VERSION_MINOR}-linux-x64.rpm"


# install nexus
RUN mkdir -p ${NEXUS_HOME} \
  && curl --fail --silent --location --retry 3 \
    https://download.sonatype.com/nexus/3/nexus-${NEXUS_VERSION}-unix.tar.gz \
  | gunzip \
  | tar x -C ${NEXUS_HOME} --strip-components=1 nexus-${NEXUS_VERSION} \
  && chown -R root:root ${NEXUS_HOME}

# configure nexus runtime env
RUN sed \
    -e "/^-Xms1200M/d" \
    -e "/^-Xmx1200M/d" \
    -e "s|karaf.home=.|karaf.home=${NEXUS_HOME}|g" \
    -e "s|karaf.base=.|karaf.base=${NEXUS_HOME}|g" \
    -e "s|karaf.etc=etc|karaf.etc=${NEXUS_HOME}/etc|g" \
    -e "s|java.util.logging.config.file=etc|java.util.logging.config.file=${NEXUS_HOME}/etc|g" \
    -e "s|karaf.data=.*|karaf.data=${NEXUS_DATA}|g" \
    -e "s|java.io.tmpdir=.*|java.io.tmpdir=${NEXUS_DATA}/tmp|g" \
    -e "s|LogFile=.*|LogFile=${NEXUS_DATA}/log/jvm.log|g" \
    -i ${NEXUS_HOME}/bin/nexus.vmoptions \
  && sed \
    -e "s|nexus-context-path=/|nexus-context-path=/\${NEXUS_CONTEXT}|g" \
    -i ${NEXUS_HOME}/etc/nexus-default.properties \
  && mkdir -p ${NEXUS_DATA}/etc ${NEXUS_DATA}/log ${NEXUS_DATA}/tmp

RUN useradd -r -u 200 -m -c "nexus role account" -d ${NEXUS_DATA} -s /bin/false nexus \
  && chown -R nexus:nexus ${NEXUS_DATA}

EXPOSE 8081
USER nexus
WORKDIR ${NEXUS_HOME}

ENV EXTRA_JAVA_OPTS "-Xms2703M -Xmx2703M -XX:MaxDirectMemorySize=2703M -XX:+UnlockExperimentalVMOptions -XX:ActiveProcessorCount=4"

CMD env INSTALL4J_ADD_VM_PARAMS="$EXTRA_JAVA_OPTS" bin/nexus run