name: Create Docker image
on: 
  workflow_dispatch:

jobs: 
  build-image:
    name: Build Docker image
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      with:
          driver: docker
    
    - name: Build Image
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: my-custom-test-repo/nexus-test
        context: service
        file: Dockerfile
        build-args: |
          NEXUS_VERSION=3.37.3-02
      
    - name: Look up images
      run: docker image ls