name: NPM Publish Workflow

on:
  workflow_call:
    inputs:
      NODE_VERSION:
        required: false
        type: string
        default: '16'
    secrets:
      NPM_TOKEN:
        required: true

jobs:
  publish:
    name: NPM Publish
    runs-on: ubuntu-latest
    steps:

      ############# CHECKOUT #############
      # https://github.com/actions/checkout
      - name: Checkout
        uses: actions/checkout@v2

      ########## SETUP #############
      # https://github.com/marketplace/actions/setup-node-js-environment
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ inputs.NODE_VERSION }}
  #        always-auth: true
  #        registry-url: ${{ env.NPM_REGISTRY_URL }}
  #        scope:        ${{ env.NPM_SCORE }}

      - name: Install dependencies
        run: npm install

      - name: Run lint checks
        run: npm run lint --if-present
        continue-on-error: true

      - name: Build
        run: npm run build --if-present

      - name: Run tests
        run: npm test
        continue-on-error: true

      ############# PUBLISH #############
      # https://github.com/marketplace/actions/npm-publish

      - name: NPM Publish
        id: publish
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          check-version: true
          dry-run: true
#          registry: ""
#          tag: ""

      - name: NPM Publish results
        run: |
          echo "Version changed: ${{ steps.publish.outputs.old-version }} => ${{ steps.publish.outputs.version }}"
          echo "Dry-run mode: ${{ steps.publish.outputs.dry-run}}"
